version: 0.2

phases:
  install:
    commands:
      # Install qemu & other utilities in the CodeBuild environment
      - apt-get update
      - apt-get install -y qemu-system-arm qemu-user-static unzip curl apt-transport-https ca-certificates
  pre_build:
    commands:
      - "echo Logging in to Docker Hub..."
      - "docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG