# Manually built and pushed Docker Hub as bboerst/rpi-qemu-alpine-python
FROM arm32v6/python:2-alpine

RUN apk add --no-cache \
	curl \
	linux-headers \
	gcc \
	musl-dev \
	jpeg-dev \
	zlib-dev \
	freetype-dev

RUN curl -L -o /usr/bin/qemu-arm-static https://github.com/multiarch/qemu-user-static/releases/download/v3.0.0/qemu-arm-static \
    && chmod +x /usr/bin/qemu-*

RUN pip install --no-cache-dir rpi.gpio spidev numpy pillow

CMD ["python"]


